[core]
  engine = pg
  top_dir = migrations

[target "db:pg:"]
  uri = db:pg://neondb_owner:npg_UsvnK9XbD6dl@ep-orange-art-ag7c8gyo-pooler.c-2.eu-central-1.aws.neon.tech/neondb
  registry = sqitch
  client = psql