-- Revert betSite-db:01.init from pg

BEGIN;

DROP TABLE IF EXISTS odds CASCADE;
DROP TABLE IF EXISTS bets CASCADE;
DROP TABLE IF EXISTS game_matches;
DROP TABLE IF EXISTS players_stats;
DROP TABLE IF EXISTS match_dragons;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS player_team_history;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS champions;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS leagues;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS users;


DROP TABLE IF EXISTS championship;

COMMIT;
