BEGIN;

INSERT INTO champions (name_champion, image) VALUES
('Aatrox', 'aatrox.png'),
('Ahri', 'ahri.png'),
('Akali', 'akali.png'),
('Akshan', 'akshan.png'),
('Alistar', 'alistar.png'),
('Ambessa', 'ambessa.png'),
('Amumu', 'amumu.png'),
('Anivia', 'anivia.png'),
('Annie', 'annie.png'),
('Aphelios', 'aphelios.png'),
('Ashe', 'ashe.png'),
('Aurelion Sol', 'aurelionSol.png'),
('Aurora', 'aurora.png'),
('Azir', 'azir.png'),
('Bard', 'bard.png'),
('Bel''veth', 'belveth.png'),
('Blitzcrank', 'blitzcrank.png'),
('Brand', 'brand.png'),
('Braum', 'braum.png'),
('Briar', 'briar.png'),
('Caitlyn', 'caitlyn.png'),
('Camille', 'camille.png'),
('Cassiopeia', 'cassiopeia.png'),
('Cho''Gath', 'choGath.png'),
('Corki', 'corki.png'),
('Darius', 'darius.png'),
('Diana', 'diana.png'),
('Draven', 'draven.png'),
('Ekko', 'ekko.png'),
('Elise', 'elise.png'),
('Evelynn', 'evelynn.png'),
('Ezreal', 'ezreal.png'),
('Fiddlesticks', 'fiddlesticks.png'),
('Fiora', 'fiora.png'),
('Fizz', 'fizz.png'),
('Galio', 'galio.png'),
('Gangplank', 'gangplank.png'),
('Garen', 'garen.png'),
('Gnar', 'gnar.png'),
('Gragas', 'gragas.png'),
('Graves', 'graves.png'),
('Gwen', 'gwen.png'),
('Heimerdinger', 'heimerdinger.png'),
('Hwei', 'hwei.png'),
('Illaoi', 'illaoi.png'),
('Irelia', 'irelia.png'),
('Ivern', 'ivern.png'),
('Janna', 'janna.png'),
('Jarvan IV', 'jarvanIV.png'),
('Jax', 'jax.png'),
('Jayce', 'jayce.png'),
('Jhin', 'jhin.png'),
('Jinx', 'jinx.png'),
('K''Sante', 'kSante.png'),
('Kai''Sa', 'kaisa.png'),
('Kalista', 'kalista.png'),
('Karma', 'karma.png'),
('Karthus', 'karthus.png'),
('Kassadin', 'kassadin.png'),
('Katarina', 'katarina.png'),
('Kayle', 'kayle.png'),
('Kayn', 'kayn.png'),
('Kennen', 'kennen.png'),
('Kha''Zix', 'khaZix.png'),
('Kindred', 'kindred.png'),
('Kled', 'kled.png'),
('Kog''Maw', 'kogMaw.png'),
('Leblanc', 'leblanc.png'),
('Lee Sin', 'leeSin.png'),
('Leona', 'leona.png'),
('Lillia', 'lillia.png'),
('Lissandra', 'lissandra.png'),
('Lucian', 'lucian.png'),
('Lulu', 'lulu.png'),
('Lux', 'lux.png'),
('Malzahar', 'malzahar.png'),
('Maokai', 'maokai.png'),
('Maître Yi', 'maitreYi.png'),
('Mel', 'mel.png'),
('Milio', 'milio.png'),
('Miss Fortune', 'missFortune.png'),
('Mordekaiser', 'mordekaiser.png'),
('Morgana', 'morgana.png'),
('Naafiri', 'naafiri.png'),
('Nami', 'nami.png'),
('Nasus', 'nasus.png'),
('Nautilus', 'nautilus.png'),
('Neeko', 'neeko.png'),
('Nidalee', 'nidalee.png'),
('Nilah', 'nilah.png'),
('Nocturne', 'nocturne.png'),
('Nunu et Willump', 'nunu.png'),
('Olaf', 'olaf.png'),
('Orianna', 'orianna.png'),
('Ornn', 'ornn.png'),
('Pantheon', 'pantheon.png'),
('Poppy', 'poppy.png'),
('Pyke', 'pyke.png'),
('Qiyana', 'qiyana.png'),
('Quinn', 'quinn.png'),
('Rakan', 'rakan.png'),
('Rammus', 'rammus.png'),
('Rek''Sai', 'rekSai.png'),
('Rell', 'rell.png'),
('Renata Glasc', 'renataGlasc.png'),
('Renekton', 'renekton.png'),
('Rengar', 'rengar.png'),
('Riven', 'riven.png'),
('Rumble', 'rumble.png'),
('Ryze', 'ryze.png'),
('Samira', 'samira.png'),
('Sejuani', 'sejuani.png'),
('Senna', 'senna.png'),
('Sett', 'sett.png'),
('Shaco', 'shaco.png'),
('Shen', 'shen.png'),
('Shyvana', 'shyvana.png'),
('Singed', 'singed.png'),
('Sion', 'sion.png'),
('Sivir', 'sivir.png'),
('Skarner', 'skarner.png'),
('Smolder', 'smolder.png'),
('Sona', 'sona.png'),
('Soraka', 'soraka.png'),
('Swain', 'swain.png'),
('Sylas', 'sylas.png'),
('Syndra', 'syndra.png'),
('Séraphine', 'seraphine.png'),
('Tahm Kench', 'tahmKench.png'),
('Taliyah', 'taliyah.png'),
('Talon', 'talon.png'),
('Taric', 'taric.png'),
('Teemo', 'teemo.png'),
('Thresh', 'thresh.png'),
('Tristana', 'tristana.png'),
('Trundle', 'trundle.png'),
('Tryndamere', 'tryndamere.png'),
('Twisted Fate', 'twistedFate.png'),
('Twitch', 'twitch.png'),
('Udyr', 'udyr.png'),
('Urgot', 'urgot.png'),
('Varus', 'varus.png'),
('Vayne', 'vayne.png'),
('Veigar', 'veigar.png'),
('Vel''koz', 'velKoz.png'),
('Vex', 'vex.png'),
('Vi', 'vi.png'),
('Viego', 'viego.png'),
('Viktor', 'viktor.png'),
('Vladimir', 'vladimir.png'),
('Volibear', 'volibear.png'),
('Warwick', 'warwick.png'),
('Wukong', 'wukong.png'),
('Xayah', 'xayah.png'),
('Xerath', 'xerath.png'),
('Xin Zhao', 'xinZhao.png'),
('Yasuo', 'yasuo.png'),
('Yone', 'yone.png'),
('Yorick', 'yorick.png'),
('Yuumi', 'yuumi.png'),
('Zac', 'zac.png'),
('Zed', 'zed.png'),
('Zeri', 'zeri.png'),
('Ziggs', 'ziggs.png'),
('Zilean', 'zilean.png'),
('Zoé', 'zoe.png'),
('Zyra', 'zyra.png');

INSERT INTO leagues (name_league, complete_name) VALUES
('LEC', 'League of Legends EMEA Championship'),
('EMEA Masters', 'EMEA Masters'),
('LTA North', 'The League of Legends Championship of The Americas North'),
('LTA South', 'The League of Legends Championship of The Americas South'),
('LFL', 'La Ligue Française'),
('LCK', 'League of Legends Champions Korea'),
('LCP', 'Pacific Championship Series'),
('LPL', 'League of Legends Pro League'),
('LJL', 'League of Legends Japan League'),
('CBLOL', 'Campeonato Brasileiro League of Legends');

INSERT INTO championship (name_championship) VALUES
('First Stand 2025');

INSERT INTO teams(name_team, id_league) VALUES
('Fnatic', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Karmine Corp', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('G2 Esports', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Movistar KOI', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Team Vitality', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('GIANTX', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Team BDS', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Team Heretics', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('SK Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Rogue', (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('Cloud9', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Dignitas', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('FlyQuest', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Lyon', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Shopify Rebellion', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Team Liquid', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('100 Thieves', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Disguised', (SELECT id_league FROM leagues WHERE name_league = 'LTA North')),
('Fluxo W7M', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('FURIA', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('Leviathan', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('LOUD', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('paIN Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('RED Canids', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('Vivo Keyd Stars', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('Isurus Estral', (SELECT id_league FROM leagues WHERE name_league = 'LTA South')),
('Vitality Bee', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Joblife', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('GameWard', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Gentle Mates', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Karmine Corp Blue', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Galions', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('BK ROG', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('BDS Academy', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Solary', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('Ici Japon Corp', (SELECT id_league FROM leagues WHERE name_league = 'LFL')),
('BNK FEARX', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('DN Freecs', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('Hanwha Life Esports', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('OKSavingsBank BRION', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('SKT T1', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('Dplus KIA', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('DRX', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('Gen.G', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('KT Rolster', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('Nongshim RedForce', (SELECT id_league FROM leagues WHERE name_league = 'LCK')),
('TOP Esports', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('LGD Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Team WE', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('JD Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Weibo Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Oh My God', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Ultra Prime', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Bilibili Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('TT Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('EDward Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('LNG Esports', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Ninjas in Pyjamas', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Invictus Gaming', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('Royal Never Give Up', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('FunPlux Phoenix', (SELECT id_league FROM leagues WHERE name_league = 'LPL')),
('CTBC Flying Oyster', (SELECT id_league FROM leagues WHERE name_league= 'LCP'));

INSERT INTO players (name_player, role, nationality) VALUES
('Oscarinin', 'TOP', 'Spain'),
('Razork', 'JUNGLE', 'Spain'),
('Humanoid', 'MID', 'Czech Republic'),
('Upset', 'ADC', 'Germany'),
('Mikyx', 'SUP', 'Slovenia'),
('Canna', 'TOP', 'South Korea'),
('Yike', 'JUNGLE', 'Sweden'),
('Vladi', 'MID', 'Greece'),
('Caliste', 'ADC', 'France'),
('Targamas', 'SUP', 'Belgium'),
('Broken Blade', 'TOP', 'Germany'),
('Skewmond', 'JUNGLE', 'France'),
('Caps', 'MID', 'Denmark'),
('Hans Sama', 'ADC', 'France'),
('Labrov', 'SUP', 'Greece'),
('Myrwn', 'TOP', 'Spain'),
('Elyoya', 'JUNGLE', 'Spain'),
('Jojopyun', 'MID', 'Canada'),
('Supa', 'ADC', 'Spain'),
('Alvaro', 'SUP', 'Spain'),
('Naak Nako', 'TOP', 'Turkey'),
('Lyncas', 'JUNGLE', 'Lithuania'),
('Czajek', 'MID', 'Poland'),
('Carzzy', 'ADC', 'Czech Republic'),
('Hylissang', 'SUP', 'Bulgaria'),
('Lot', 'TOP', 'Turkey'),
('Closer', 'JUNGLE', 'Turkey'),
('Jackies', 'MID', 'Czech Republic'),
('Noah', 'ADC', 'South Korea'),
('Jun', 'SUP', 'South Korea'),
('Irrelevant', 'TOP', 'Germany'),
('113', 'JUNGLE', 'Turkey'),
('nuc', 'MID', 'France'),
('Ice', 'ADC', 'South Korea'),
('Parus', 'SUP', 'Turkey'),
('Carlsen', 'TOP', 'Denmark'),
('Sheo', 'JUNGLE', 'France'),
('Kamiloo', 'MID', 'France'),
('Flakked', 'ADC', 'Spain'),
('Stend', 'SUP', 'Stend'),
('JNX', 'TOP', 'Germany'),
('ISMA', 'JUNGLE', 'France'),
('RKR', 'MID', 'Germany'),
('Rahel', 'ADC', 'South Korea'),
('Loopy', 'SUP', 'South Korea'),
('Adam', 'TOP', 'France'),
('Malrang', 'JUNGLE', 'South Korea'),
('Larssen', 'MID', 'Sweden'),
('Patrick', 'ADC', 'Czech Republic'),
('Execute', 'SUP', 'South Korea');

INSERT INTO player_team_history (id_player, id_team, start_date, end_date) VALUES
((SELECT id_player FROM players WHERE name_player = 'Oscarinin'),
  (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Razork'),
  (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Humanoid'),
  (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Upset'),
  (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Mikyx'),
  (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Canna'),
  (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Yike'),
  (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Vladi'),
  (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Caliste'),
  (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Targamas'),
  (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Broken Blade'),
  (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Skewmond'),
  (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Caps'),
  (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Hans Sama'),
  (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Labrov'),
  (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Myrwn'),
  (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Elyoya'),
  (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Jojopyun'),
  (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Supa'),
  (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Alvaro'),
  (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Naak Nako'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Lyncas'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Czajek'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Carzzy'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Hylissang'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Lot'),
  (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Closer'),
  (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Jackies'),
  (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Noah'),
  (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Jun'),
  (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Irrelevant'),
  (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = '113'),
  (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'nuc'),
  (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Ice'),
  (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Parus'),
  (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Carlsen'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Sheo'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Kamiloo'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Flakked'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Stend'),
  (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'JNX'),
  (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'ISMA'),
  (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'RKR'),
  (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Loopy'),
  (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Rahel'),
  (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Adam'),
  (SELECT id_team FROM teams WHERE name_team = 'Rogue'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Malrang'),
  (SELECT id_team FROM teams WHERE name_team = 'Rogue'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Larssen'),
  (SELECT id_team FROM teams WHERE name_team = 'Rogue'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Patrick'),
  (SELECT id_team FROM teams WHERE name_team = 'Rogue'), '2025-01-01', NULL),
((SELECT id_player FROM players WHERE name_player = 'Execute'),
  (SELECT id_team FROM teams WHERE name_team = 'Rogue'), '2025-01-01', NULL);

/*
INSERT INTO matches (date_match, team1, team2, victoire, id_league) VALUES
('2025-01-18', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-18', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-18', 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-18', 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-18', 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-19', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-19', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-19', 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-19', 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-19', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-20', 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-20', 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-20', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-20', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-20', 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-25', 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-25', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-25', 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-25', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-25', 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-26', 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-26', 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-26', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-26', 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-26', 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-27', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-27', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-27', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-27', 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-01-27', 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-01', 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-01', 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-01', 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-01', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-01', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-02', 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-02', 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-02', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-02', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-02', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-03', 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Vitality'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-03', 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Rogue'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-03', 
    (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team BDS'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-03', 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_team FROM teams WHERE name_team = 'Team Heretics'), 
    (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC')),
('2025-02-03', 
    (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC'));

INSERT INTO matches (date_match, team1, team2, victoire, id_league, game_number) VALUES 
('2025-02-28', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC'),
    1),
('2025-02-28', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC'),
    2),
('2025-02-28', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC'),
    3),
('2025-02-28', 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
    (SELECT id_league FROM leagues WHERE name_league = 'LEC'),
    4);


INSERT INTO games (id_match, winner_team) VALUES
((SELECT id_match FROM matches
  WHERE date_match = '2025-01-18' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-18' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-18' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'GIANTX')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-18' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-18' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')), 
 (SELECT id_team FROM teams WHERE name_team = 'Rogue')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-19' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-19' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team BDS')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-19' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-19' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'GIANTX')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-19' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-20' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-20' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team BDS')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-20' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-20' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-20' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')), 
 (SELECT id_team FROM teams WHERE name_team = 'GIANTX')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-25' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-25' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-25' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-25' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-25' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-26' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')), 
 (SELECT id_team FROM teams WHERE name_team = 'GIANTX')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-26' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-26' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-26' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-26' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-27' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-27' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-27' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-27' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-01-27' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-01' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team BDS')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-01' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-01' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-01' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-01' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')), 
 (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-02' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')), 
 (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-02' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'GIANTX')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-02' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-02' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-02' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-03' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'GIANTX')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team Vitality')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-03' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Rogue')), 
 (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-03' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team BDS')), 
 (SELECT id_team FROM teams WHERE name_team = 'Team BDS')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-03' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Team Heretics')), 
 (SELECT id_team FROM teams WHERE name_team = 'G2 Esports')),
((SELECT id_match FROM matches 
  WHERE date_match = '2025-02-03' 
  AND team1 = (SELECT id_team FROM teams WHERE name_team = 'SK Gaming')
  AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')), 
 (SELECT id_team FROM teams WHERE name_team = 'Fnatic'));


INSERT INTO games (id_match, winner_team, game_number) VALUES
(
    (SELECT id_match FROM matches 
     WHERE date_match = '2025-02-28' 
     AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
     AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
     AND game_number = 1),  
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'),
    1
),
(
    (SELECT id_match FROM matches 
     WHERE date_match = '2025-02-28' 
     AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
     AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
     AND game_number = 2),  
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'),
    2
),
(
    (SELECT id_match FROM matches 
     WHERE date_match = '2025-02-28' 
     AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
     AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
     AND game_number = 3),  
    (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'),
    3
),
(
    (SELECT id_match FROM matches 
     WHERE date_match = '2025-02-28' 
     AND team1 = (SELECT id_team FROM teams WHERE name_team = 'Fnatic')
     AND team2 = (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI')
     AND game_number = 4),  
    (SELECT id_team FROM teams WHERE name_team = 'Fnatic'),
    4
);

INSERT INTO players_stats (id_match, id_player, id_team, id_champion, kills, deaths, assists, gold_earned, cs) 
VALUES 
    (1, (SELECT id_player FROM players WHERE name_player = 'Broken Blade'), 
        (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Gragas'), 
        1, 5, 4, 12661, 289),

    (1, (SELECT id_player FROM players WHERE name_player = 'Skewmond'), 
        (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Wukong'), 
        1, 3, 7, 12359, 245),

    (1, (SELECT id_player FROM players WHERE name_player = 'Caps'), 
        (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Akali'), 
        7, 4, 0, 16121, 316),

    (1, (SELECT id_player FROM players WHERE name_player = 'Hans Sama'), 
        (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Miss Fortune'), 
        3, 3, 5, 16200, 381),

    (1, (SELECT id_player FROM players WHERE name_player = 'Labrov'), 
        (SELECT id_team FROM teams WHERE name_team = 'G2 Esports'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Rell'), 
        1, 7, 4, 7900, 30),

    (1, (SELECT id_player FROM players WHERE name_player = 'Canna'), 
        (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Jayce'), 
        5, 3, 11, 16800, 303),
    (1, (SELECT id_player FROM players WHERE name_player = 'Yike'), 
        (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Sejuani'), 
        6, 3, 9, 13200, 192),
    (1, (SELECT id_player FROM players WHERE name_player = 'Vladi'), 
        (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Viktor'), 
        6, 3, 10, 17500, 350),
    (1, (SELECT id_player FROM players WHERE name_player = 'Caliste'), 
        (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Ezreal'), 
        5, 1, 9, 18400, 392),
    (1, (SELECT id_player FROM players WHERE name_player = 'Targamas'), 
        (SELECT id_team FROM teams WHERE name_team = 'Karmine Corp'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Alistar'), 
        0, 3, 17, 9500, 27),
    (2, (SELECT id_player FROM players WHERE name_player = 'Myrwn'), 
        (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'K''Sante'), 
        1, 0, 10, 11100, 219),
    (2, (SELECT id_player FROM players WHERE name_player = 'Elyoya'), 
        (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Skarner'), 
        3, 0, 12, 10400, 164),
    (2, (SELECT id_player FROM players WHERE name_player = 'Jojopyun'), 
        (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Azir'), 
        3, 1, 10, 13700, 249),
    (2, (SELECT id_player FROM players WHERE name_player = 'Supa'), 
        (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Varus'), 
        11, 1, 8, 16000, 283),
    (2, (SELECT id_player FROM players WHERE name_player = 'Alvaro'), 
        (SELECT id_team FROM teams WHERE name_team = 'Movistar KOI'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Rell'), 
        1, 0, 17, 8600, 24),
    (2, (SELECT id_player FROM players WHERE name_player = 'Oscarinin'), 
        (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Jax'), 
        0, 5, 1, 9100, 207),
    (2, (SELECT id_player FROM players WHERE name_player = 'Razork'), 
        (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Ivern'), 
        0, 4, 2, 9300, 170),
    (2, (SELECT id_player FROM players WHERE name_player = 'Humanoid'), 
        (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Viktor'), 
        0, 2, 1, 10300, 268),
    (2, (SELECT id_player FROM players WHERE name_player = 'Upset'), 
        (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Miss Fortune'), 
        1, 2, 0, 11700, 290),
    (2, (SELECT id_player FROM players WHERE name_player = 'Mikyx'), 
        (SELECT id_team FROM teams WHERE name_team = 'Fnatic'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Alistar'), 
        1, 6, 1, 6600, 22),
    (3, (SELECT id_player FROM players WHERE name_player = 'Lot'), 
        (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Jax'), 
        7, 2, 6, 16000, 297),
    (3, (SELECT id_player FROM players WHERE name_player = 'Closer'), 
        (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Maokai'), 
        1, 2, 12, 10400, 160),
    (3, (SELECT id_player FROM players WHERE name_player = 'Jackies'), 
        (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Viktor'), 
        4, 0, 8, 15200, 320),
    (3, (SELECT id_player FROM players WHERE name_player = 'Noah'), 
        (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Ezreal'), 
        5, 0, 9, 16000, 331),
    (3, (SELECT id_player FROM players WHERE name_player = 'Jun'), 
        (SELECT id_team FROM teams WHERE name_team = 'GIANTX'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Rell'), 
        2, 1, 15, 9800, 45),
    (3, (SELECT id_player FROM players WHERE name_player = 'JNX'), 
        (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Jayce'), 
        0, 5, 2, 11000, 259),
    (3, (SELECT id_player FROM players WHERE name_player = 'ISMA'), 
        (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Xin Zhao'), 
        0, 5, 4, 9700, 193),
    (3, (SELECT id_player FROM players WHERE name_player = 'RKR'), 
        (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Galio'), 
        1, 1, 2, 11700, 293),
    (3, (SELECT id_player FROM players WHERE name_player = 'Rahel'), 
        (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Jinx'), 
        3, 3, 1, 14400, 298),
    (3, (SELECT id_player FROM players WHERE name_player = 'Loopy'), 
        (SELECT id_team FROM teams WHERE name_team = 'SK Gaming'), 
        (SELECT id_champion FROM champions WHERE name_champion = 'Braum'), 
        1, 5, 4, 8200, 19);


INSERT INTO games (game_number, winner_team)
VALUES (5, NULL);  

INSERT INTO game_matches (id_game, id_match)
VALUES 
((SELECT id_game FROM games WHERE game_number = 5 ORDER BY id_game DESC LIMIT 1),
 (SELECT id_match FROM matches WHERE date_match = '2025-02-28' AND game_number = 1)),

((SELECT id_game FROM games WHERE game_number = 5 ORDER BY id_game DESC LIMIT 1),
 (SELECT id_match FROM matches WHERE date_match = '2025-02-28' AND game_number = 2)),

((SELECT id_game FROM games WHERE game_number = 5 ORDER BY id_game DESC LIMIT 1),
 (SELECT id_match FROM matches WHERE date_match = '2025-02-28' AND game_number = 3)),

((SELECT id_game FROM games WHERE game_number = 5 ORDER BY id_game DESC LIMIT 1),
 (SELECT id_match FROM matches WHERE date_match = '2025-02-28' AND game_number = 4));

*/

INSERT INTO games (bo, winner_team) VALUES
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(3, NULL),
(5, NULL),
(5, NULL),
(5, NULL),
(1, NULL);

INSERT INTO matches (date_match, team1, team2, victoire, id_championship, game_number) VALUES 
('2025-03-10 09:00:00', 16, 2, NULL, 1, 1),
('2025-03-10 09:00:00', 16, 2, NULL, 1, 2),
('2025-03-10 09:00:00', 16, 2, NULL, 1, 3),
('2025-03-10 12:00:00', 39, 47, NULL, 1, 1),
('2025-03-10 12:00:00', 39, 47, NULL, 1, 2),
('2025-03-10 12:00:00', 39, 47, NULL, 1, 3),
('2025-03-11 09:00:00', 62, 2, NULL, 1, 1),
('2025-03-11 09:00:00', 62, 2, NULL, 1, 2),
('2025-03-11 09:00:00', 62, 2, NULL, 1, 3),
('2025-03-11 12:00:00', 16, 47, NULL, 1, 1),
('2025-03-11 12:00:00', 16, 47, NULL, 1, 2),
('2025-03-11 12:00:00', 16, 47, NULL, 1, 3),
('2025-03-12 09:00:00', 62, 39, NULL, 1, 1),
('2025-03-12 09:00:00', 62, 39, NULL, 1, 2),
('2025-03-12 09:00:00', 62, 39, NULL, 1, 3),
('2025-03-12 12:00:00', 2, 47, NULL, 1, 1),
('2025-03-12 12:00:00', 2, 47, NULL, 1, 2),
('2025-03-12 12:00:00', 2, 47, NULL, 1, 3),
('2025-03-13 09:00:00', 16, 62, NULL, 1, 1),
('2025-03-13 09:00:00', 16, 62, NULL, 1, 2),
('2025-03-13 09:00:00', 16, 62, NULL, 1, 3),
('2025-03-13 12:00:00', 2, 39, NULL, 1, 1),
('2025-03-13 12:00:00', 2, 39, NULL, 1, 2),
('2025-03-13 12:00:00', 2, 39, NULL, 1, 3),
('2025-03-14 09:00:00', 62, 47, NULL, 1, 1),
('2025-03-14 09:00:00', 62, 47, NULL, 1, 2),
('2025-03-14 09:00:00', 62, 47, NULL, 1, 3),
('2025-03-14 12:00:00', 16, 39, NULL, 1, 1),
('2025-03-14 12:00:00', 16, 39, NULL, 1, 2),
('2025-03-14 12:00:00', 16, 39, NULL, 1, 3),
('2025-03-15 05:00:00', 62, 2, NULL, 1, 1),
('2025-03-15 05:00:00', 62, 2, NULL, 1, 2),
('2025-03-15 05:00:00', 62, 2, NULL, 1, 3),
('2025-03-15 10:00:00', 39, 47, NULL, 1, 1),
('2025-03-15 10:00:00', 39, 47, NULL, 1, 2),
('2025-03-15 10:00:00', 39, 47, NULL, 1, 3),
('2025-03-16 09:00:00', 39, 2, NULL, 1, 1),
('2025-03-16 09:00:00', 39, 2, NULL, 1, 2),
('2025-03-16 09:00:00', 39, 2, NULL, 1, 3),
('2025-03-16 09:00:00', 39, 2, NULL, 1, 4),
('2025-03-16 09:00:00', 39, 2, NULL, 1, 5),
('2025-03-18 09:00:00', 5,4,NULL, 1,1);



INSERT INTO game_matches (id_game, id_match) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 5),
(2, 6),
(3, 7),
(3, 8),
(3, 9),
(4, 10),
(4, 11),
(4, 12),
(5, 13),
(5, 14),
(5, 15),
(6, 16),
(6, 17),
(6, 18),
(7, 19),
(7, 20),
(7, 21),
(8, 22),
(8, 23),
(8, 24),
(9, 25),
(9, 26),
(9, 27),
(10, 28),
(10, 29),
(10, 30),
(11, 31),
(11, 32),
(11, 33),
(12, 34),
(12, 35),
(12, 36),
(13, 37),
(13, 38),
(13, 39),
(13, 40),
(13, 41),
(14, 42);

INSERT INTO odds (id_game, id_team, odds) VALUES
(9, 62, 9),
(9, 47, 1.05),
(10, 16, 12),
(10, 39, 1.03),
(11, 62, 1.71),
(11, 2, 2.10),
(12, 39, 1.17),
(12, 47, 4.80),
(13, 39, 1.05),
(13, 2, 9),
(14, 5, 2.5),
(14, 4, 1.8);

COMMIT;

